# Generated by Django 3.1.12 on 2025-11-20 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('entreprise', models.CharField(blank=True, max_length=150)),
                ('statutCompte', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=10)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
